import { FlatCompat } from '@eslint/eslintrc';
import tseslint from 'typescript-eslint';

const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

/**
 * The ESLint CLI rather than `next lint`, which is deprecated and removed in Next.js 16.
 *
 * `eslint-config-next` still ships as eslintrc-shaped config, so it comes in through `FlatCompat`;
 * that is the migration path Next documents, not a workaround.
 */
export default tseslint.config(
  {
    // The generated client types and Next's build output. Linting `api-schema.d.ts` would report on a
    // file no one edits — the fix for anything found there is upstream, in the OpenAPI document.
    // `next-env.d.ts` is regenerated by every build and carries the triple-slash reference the
    // TypeScript rule forbids, so linting it reports a finding no one can fix.
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      'src/lib/api-schema.d.ts',
      'playwright-report/**',
    ],
  },
  ...compat.extends('next/core-web-vitals'),
  ...tseslint.configs.recommended,
  {
    rules: {
      // Unused arguments named with a leading underscore are the repo's way of saying "this position
      // exists because the signature requires it".
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
    },
  },
);
